ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '. ';
-- Table Movie
CREATE TABLE Movie (
    movie_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(255),
    release_date DATE,
    runtime NUMBER,
    vote_average VARCHAR(50),
    vote_count NUMBER,
    adult VARCHAR2(100), 
    original_language VARCHAR2(150),
    overview VARCHAR2(1100),
    popularity VARCHAR(50),
    tagline VARCHAR2(255)
);
 
-- Table Genre
CREATE TABLE Genre (
    genre_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    genre_name VARCHAR2(255)
);

-- Table Movie_Genre (relation entre films et genres)
CREATE TABLE Movie_Genre (
    movie_id NUMBER,
    genre_id NUMBER
);

-- Table Users (acheteurs)
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    age NUMBER,
    role VARCHAR(50)
);

-- Table Rental (locations)
CREATE TABLE Rental (
    rental_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    movie_id NUMBER,
    rental_date DATE,
    end_date GENERATED ALWAYS AS (rental_date + 15) VIRTUAL
);

-- Table Rating (notes)
CREATE TABLE Rating (
    rating_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    movie_id NUMBER,
    rating_value NUMBER(4, 2),
    review VARCHAR2(1100)
);

-- Table Production_Company (compagnies de production)
CREATE TABLE Production_Company (
    company_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255)
);

-- Table Movie_Production_Company (relation entre films et compagnies de production)
CREATE TABLE Movie_Production_Company (
    movie_id NUMBER,
    company_id NUMBER
);

CREATE TABLE Monthly_Report (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    report_month DATE,
    movie_id NUMBER,
    title VARCHAR2(255),
    vote_average NUMBER(4, 2),
    popularity VARCHAR2(50)
);

-- PRIMARY KEYS
ALTER TABLE Movie ADD CONSTRAINT pk_movie PRIMARY KEY (movie_id);
ALTER TABLE Genre ADD CONSTRAINT pk_genre PRIMARY KEY (genre_id);
ALTER TABLE Movie_Genre ADD CONSTRAINT pk_movie_genre PRIMARY KEY (movie_id, genre_id);
ALTER TABLE Users ADD CONSTRAINT pk_users PRIMARY KEY (user_id);
ALTER TABLE Rental ADD CONSTRAINT pk_rental PRIMARY KEY (rental_id);
ALTER TABLE Rating ADD CONSTRAINT pk_rating PRIMARY KEY (rating_id);
ALTER TABLE Production_Company ADD CONSTRAINT pk_production_company PRIMARY KEY (company_id);
ALTER TABLE Movie_Production_Company ADD CONSTRAINT pk_movie_production_company PRIMARY KEY (movie_id, company_id);

-- FOREIGN KEYS
ALTER TABLE Movie_Genre ADD CONSTRAINT fk_movie_genre_movie FOREIGN KEY (movie_id) REFERENCES Movie(movie_id);
ALTER TABLE Movie_Genre ADD CONSTRAINT fk_movie_genre_genre FOREIGN KEY (genre_id) REFERENCES Genre(genre_id);

ALTER TABLE Rental ADD CONSTRAINT fk_rental_user FOREIGN KEY (user_id) REFERENCES Users(user_id);
ALTER TABLE Rental ADD CONSTRAINT fk_rental_movie FOREIGN KEY (movie_id) REFERENCES Movie(movie_id);

ALTER TABLE Rating ADD CONSTRAINT fk_rating_user FOREIGN KEY (user_id) REFERENCES Users(user_id);
ALTER TABLE Rating ADD CONSTRAINT fk_rating_movie FOREIGN KEY (movie_id) REFERENCES Movie(movie_id);

ALTER TABLE Movie_Production_Company ADD CONSTRAINT fk_movie_production_company_movie FOREIGN KEY (movie_id) REFERENCES Movie(movie_id);
ALTER TABLE Movie_Production_Company ADD CONSTRAINT fk_movie_production_company FOREIGN KEY (company_id) REFERENCES Production_Company(company_id);
